name: 'Jest coverage referencing main branch existing summary validate only latest changes'
description: 'A github action to comment jest coverage diff on a PR using current branch vs already existing main branch summary'
author: 'Zuki Sarusi'
inputs:
  accessToken:
    description: 'access token required to comment on a pr'
    default: ${{ github.token }}

  fullCoverageDiff:
    description: 'get the full coverage with diff or only the diff'
    default: false

  runCommand:
    description: 'custom command to get json-summary'
    default: 'npx jest --coverage --coverageReporters="json-summary" --coverageDirectory="./"'

  delta:
    description: 'Difference between the old and final test coverage'
    default: 100

  total_delta:
    description: 'Difference between the old and final test coverage at the total level'
    default: null

  useSameComment:
    description: 'While commenting on the PR update the exisiting comment'
    default: false

  mainBranchCoverageSummaryFileName:
    description: 'file name of main branch summary (master)'
    default: 'develop-coverage-summary.json'

  additionalCommentInfo:
    description: 'Additional string that will be concatenated to comment'
    default: null

  codeCoverageDirectory:
    description: 'code coverage summary location defaults to coverage-summary.json'
    default: coverage-summary.json
branding:
  color: red
  icon: git-pull-request
runs:
  using: 'node12'
  main: 'dist/index.js'
